# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0002_auto_20170718_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Working'), (1, 'OnVacation')], default=0, null=True),
        ),
    ]
