# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_app', '0003_auto_20170718_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
